import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Script from "next/script";
import { useState } from "react";
import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";
const Home: NextPage = () => {
  const [amount, setAmount] = useState<number>(1);

  return (
    <div className={styles.container}>
      <Head>
        <title>CazzPay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PayPalScriptProvider
        options={{
          "client-id": process.env.NEXT_PUBLIC_CLIENT_ID as string,
        }}
      >
        <main className={styles.main}>
          <span id="loginBtn"></span>
          <label>Enter amount</label>
          <input
            style={{
              marginBottom: "12px",
            }}
            type="number"
            placeholder="enter amount"
            defaultValue={1}
            onChange={(e) => setAmount(parseInt(e.target.value))}
            min={1}
          />
          <PayPalButtons
            style={{
              layout: "horizontal",
              color: "blue",
              shape: "pill",
            }}
            forceReRender={[amount]}
            createOrder={async () => {
              try {
                const res = await fetch("/api/orders", {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                    Accept: "application/json",
                  },
                  body: JSON.stringify({
                    price: `${amount}.00`,
                  }),
                });
                const data = await res.json();
                return data.id;
              } catch (e) {
                console.error(e);
              }
            }}
            onCancel={(data) => console.log("Canceled")}
            onApprove={async (data, actions) => {
              const res = await fetch(`/api/orders/${data.orderID}`, {
                method: "post",
              });
              const order = await res.json();
              console.log(order);
            }}
          />
        </main>
      </PayPalScriptProvider>
    </div>
  );
};

export default Home;
